// ── Jewelry templates for quick-start POD designs ────────────────────────────

export const TEMPLATES = [
  // ── Letter / Initial pendants ─────────────────────────────────────────────
  {
    id: "letter-pendant",
    category: "initials",
    label: "Initial Pendant",
    description: "Personalized letter charm with bail",
    icon: "A",
    supportsText: true,
    textLabel: "Letter (A–Z)",
    textMaxLen: 1,
    preview: "circle",
    config: {
      type: "pendant",
      material: "silver",
      finish: "polished",
      pattern: "none",
      engraving: "A",
      pendant: { shape: "circle", width: 18, height: 18, depth: 2.5, bailWidth: 4, bailHeight: 6 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 4, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "letter-tag",
    category: "initials",
    label: "Letter Tag",
    description: "Rectangular tag with engraved initial",
    icon: "T",
    supportsText: true,
    textLabel: "Letter (A–Z)",
    textMaxLen: 1,
    config: {
      type: "pendant",
      material: "gold",
      finish: "polished",
      pattern: "none",
      engraving: "B",
      pendant: { shape: "square", width: 16, height: 20, depth: 2.5, bailWidth: 4, bailHeight: 5 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "shield-initial",
    category: "initials",
    label: "Shield Initial",
    description: "Heraldic shield with your letter",
    icon: "S",
    supportsText: true,
    textLabel: "Letter (A–Z)",
    textMaxLen: 1,
    config: {
      type: "pendant",
      material: "silver",
      finish: "matte",
      pattern: "none",
      engraving: "C",
      pendant: { shape: "shield", width: 16, height: 22, depth: 3, bailWidth: 4, bailHeight: 6 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },

  // ── Name / word jewelry ───────────────────────────────────────────────────
  {
    id: "name-pendant",
    category: "names",
    label: "Name Pendant",
    description: "Elongated pendant for short names",
    icon: "≡",
    supportsText: true,
    textLabel: "Name (max 6 chars)",
    textMaxLen: 6,
    config: {
      type: "pendant",
      material: "gold",
      finish: "polished",
      pattern: "none",
      engraving: "LUNA",
      pendant: { shape: "square", width: 40, height: 12, depth: 2, bailWidth: 5, bailHeight: 5 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "name-ring",
    category: "names",
    label: "Name Ring",
    description: "Band engraved with a name inside",
    icon: "◎",
    supportsText: true,
    textLabel: "Name / word",
    textMaxLen: 12,
    config: {
      type: "ring",
      material: "silver",
      finish: "polished",
      pattern: "none",
      engraving: "forever",
      ring: { innerRadius: 8.25, bandWidth: 6, thickness: 1.6, profile: "flat", signetWidth: 10, signetHeight: 12 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "word-bracelet",
    category: "names",
    label: "Word Bracelet",
    description: "Bangle with word/phrase engraved",
    icon: "○",
    supportsText: true,
    textLabel: "Word / phrase",
    textMaxLen: 20,
    config: {
      type: "bracelet",
      material: "silver",
      finish: "polished",
      pattern: "none",
      engraving: "strength",
      bracelet: { style: "bangle", innerDiameter: 58, width: 8, thickness: 1.8, cuffOpening: 20, linkSize: 8 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },

  // ── Birthstone / gem pieces ───────────────────────────────────────────────
  {
    id: "birthstone-pendant",
    category: "birthstone",
    label: "Birthstone Pendant",
    description: "Teardrop with bezel-set birthstone",
    icon: "◆",
    config: {
      type: "pendant",
      material: "silver",
      finish: "polished",
      pattern: "none",
      engraving: "",
      pendant: { shape: "teardrop", width: 14, height: 20, depth: 3, bailWidth: 4, bailHeight: 6 },
      stone: { setting: "bezel", shape: "round", gem: "sapphire", sizeMm: 6, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "birthstone-ring",
    category: "birthstone",
    label: "Birthstone Ring",
    description: "Prong-set solitaire ring",
    icon: "◎",
    config: {
      type: "ring",
      material: "gold",
      finish: "polished",
      pattern: "none",
      engraving: "",
      ring: { innerRadius: 8.25, bandWidth: 4, thickness: 1.4, profile: "comfort", signetWidth: 10, signetHeight: 12 },
      stone: { setting: "prong", shape: "round", gem: "ruby", sizeMm: 5, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "eternity-band",
    category: "birthstone",
    label: "Eternity Band",
    description: "Pavé diamonds all the way around",
    icon: "◎",
    config: {
      type: "ring",
      material: "gold",
      finish: "polished",
      pattern: "none",
      engraving: "",
      ring: { innerRadius: 8.25, bandWidth: 4, thickness: 1.6, profile: "flat", signetWidth: 10, signetHeight: 12 },
      stone: { setting: "pave", shape: "round", gem: "diamond", sizeMm: 2.5, count: 9, placementAngle: 0 },
    },
  },

  // ── Geometric / minimal ───────────────────────────────────────────────────
  {
    id: "hexagon-pendant",
    category: "geometric",
    label: "Hex Pendant",
    description: "Minimal hexagonal form",
    icon: "⬡",
    config: {
      type: "pendant",
      material: "silver",
      finish: "brushed",
      pattern: "none",
      engraving: "",
      pendant: { shape: "hexagon", width: 20, height: 22, depth: 2.5, bailWidth: 4, bailHeight: 5 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "stacking-ring",
    category: "geometric",
    label: "Stacking Ring",
    description: "Thin minimalist stacker",
    icon: "◎",
    config: {
      type: "ring",
      material: "rose-gold",
      finish: "polished",
      pattern: "none",
      engraving: "",
      ring: { innerRadius: 8.25, bandWidth: 2.5, thickness: 1.2, profile: "knife-edge", signetWidth: 10, signetHeight: 12 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "signet-ring",
    category: "geometric",
    label: "Signet Ring",
    description: "Classic flat-face signet",
    icon: "◻",
    supportsText: true,
    textLabel: "Initials (2–3 chars)",
    textMaxLen: 3,
    config: {
      type: "ring",
      material: "gold",
      finish: "matte",
      pattern: "none",
      engraving: "JD",
      ring: { innerRadius: 9.5, bandWidth: 8, thickness: 2.2, profile: "signet", signetWidth: 14, signetHeight: 16 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "star-pendant",
    category: "geometric",
    label: "Star Charm",
    description: "5-point star with lattice texture",
    icon: "★",
    config: {
      type: "pendant",
      material: "gold",
      finish: "polished",
      pattern: "lattice",
      patternDepth: 0.4,
      patternScale: 1.2,
      engraving: "",
      pendant: { shape: "star", width: 20, height: 20, depth: 2.5, bailWidth: 3.5, bailHeight: 5 },
      stone: { setting: "flush", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "leaf-pendant",
    category: "geometric",
    label: "Leaf Pendant",
    description: "Organic leaf form",
    icon: "🌿",
    config: {
      type: "pendant",
      material: "silver",
      finish: "hammered",
      pattern: "none",
      engraving: "",
      pendant: { shape: "leaf", width: 14, height: 28, depth: 2.5, bailWidth: 3.5, bailHeight: 5 },
      stone: { setting: "none", shape: "round", gem: "emerald", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },

  // ── Hoops / earrings ──────────────────────────────────────────────────────
  {
    id: "hoop-earring",
    category: "earrings",
    label: "Classic Hoop",
    description: "Simple round hoop earring",
    icon: "◯",
    config: {
      type: "earring",
      material: "gold",
      finish: "polished",
      pattern: "none",
      engraving: "",
      earring: { shape: "hoop-thin", size: 10, thickness: 1.5, dropLength: 20, hoopDiameter: 24, hoopThickness: 1.4 },
      stone: { setting: "none", shape: "round", gem: "diamond", sizeMm: 3, count: 1, placementAngle: 0 },
    },
  },
  {
    id: "drop-earring",
    category: "earrings",
    label: "Teardrop Drop",
    description: "Elegant drop earring",
    icon: "◈",
    config: {
      type: "earring",
      material: "silver",
      finish: "polished",
      pattern: "none",
      engraving: "",
      earring: { shape: "drop-teardrop", size: 12, thickness: 1.5, dropLength: 30, hoopDiameter: 20, hoopThickness: 1.5 },
      stone: { setting: "bezel", shape: "oval", gem: "amethyst", sizeMm: 6, count: 1, placementAngle: 0 },
    },
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: "all",        label: "All" },
  { id: "initials",   label: "Initials" },
  { id: "names",      label: "Names" },
  { id: "birthstone", label: "Birthstone" },
  { id: "geometric",  label: "Geometric" },
  { id: "earrings",   label: "Earrings" },
];