// Demo stores and artifacts for explore page
// These are shown when the database has no published items

export const DEMO_STORES = [
  {
    id: "demo-store-1",
    handle: "kaiform",
    display_name: "kai form",
    bio: "cad designer working at the intersection of jewelry and architecture. based in berlin.",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop&auto=format",
    banner_url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&h=300&fit=crop&auto=format",
    accent_color: "#84A48B",
    materials: ["silver", "brass", "gold"],
    tools: ["rhino", "grasshopper", "blender"],
    commission_open: true,
    hourly_rate: 80,
    turnaround_time: "2-3 weeks",
    store_heading: "objects at the edge of computation",
    social_instagram: "kaiform",
    _isDemo: true,
  },
  {
    id: "demo-store-2",
    handle: "orbitobjects",
    display_name: "orbit objects",
    bio: "sculptural wearables and functional objects. every piece is a conversation between material and form.",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&auto=format",
    banner_url: "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?w=800&h=300&fit=crop&auto=format",
    accent_color: "#558E9B",
    materials: ["silver", "brass"],
    tools: ["fusion 360", "keyshot"],
    commission_open: false,
    store_heading: "gravity-defying metal objects",
    social_instagram: "orbitobjects",
    _isDemo: true,
  },
  {
    id: "demo-store-3",
    handle: "voidcraft",
    display_name: "void craft",
    bio: "minimal, precise, considered. parametric jewelry from amsterdam.",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop&auto=format",
    banner_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=300&fit=crop&auto=format",
    accent_color: "#A386A9",
    materials: ["gold", "silver"],
    tools: ["rhino", "modo"],
    commission_open: true,
    hourly_rate: 120,
    turnaround_time: "3-4 weeks",
    store_heading: "precision in precious metals",
    _isDemo: true,
  },
];

export const DEMO_ARTIFACTS = [
  {
    id: "demo-1",
    name: "signet_01",
    description: "a bold, flat-faced signet ring with chamfered edges and a recessed surface. designed for engraving or wearing as is. inspired by roman wax seals and brutalist architecture.",
    image_url: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&h=600&fit=crop&auto=format",
    creator_handle: "kaiform",
    creator_name: "kai form",
    category: "jewelry",
    materials: ["silver", "brass", "gold"],
    prices: { silver: 185, brass: 110, gold: 480 },
    manufacturing_costs: { silver: 95, brass: 60, gold: 280 },
    creator_earnings: { silver: 90, brass: 50, gold: 200 },
    specs: "18mm face, size 6-12",
    region: "europe",
    status: "published",
    made_to_order: true,
    is_featured: true,
    _isDemo: true,
  },
  {
    id: "demo-2",
    name: "arch_pendant_03",
    description: "a suspended arch form, cast in solid metal with a polished inner surface and brushed exterior. hangs from a fine chain or cord. a quiet architectural presence at the collar.",
    image_url: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=600&h=600&fit=crop&auto=format",
    creator_handle: "kaiform",
    creator_name: "kai form",
    category: "jewelry",
    materials: ["silver", "gold"],
    prices: { silver: 220, gold: 560 },
    manufacturing_costs: { silver: 110, gold: 320 },
    creator_earnings: { silver: 110, gold: 240 },
    specs: "32mm height, includes chain",
    region: "global",
    status: "published",
    made_to_order: true,
    _isDemo: true,
  },
  {
    id: "demo-3",
    name: "orbit_cuff_07",
    description: "an open bangle with asymmetric orbital detail on one terminus. the weight distribution is intentional - it settles on the wrist in a way that feels inevitable.",
    image_url: "https://images.unsplash.com/photo-1573408301185-9519f94815b2?w=600&h=600&fit=crop&auto=format",
    creator_handle: "orbitobjects",
    creator_name: "orbit objects",
    category: "wearable",
    materials: ["silver", "brass"],
    prices: { silver: 310, brass: 190 },
    manufacturing_costs: { silver: 160, brass: 90 },
    creator_earnings: { silver: 150, brass: 100 },
    specs: "65mm inner diameter, 8mm profile",
    region: "north_america",
    status: "published",
    made_to_order: true,
    _isDemo: true,
  },
  {
    id: "demo-4",
    name: "vessel_02",
    description: "a small object for holding. inspired by ancient reliquaries, scaled down to the size of a cupped hand. solid brass with a polished interior cavity.",
    image_url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&h=600&fit=crop&auto=format",
    creator_handle: "orbitobjects",
    creator_name: "orbit objects",
    category: "sculpture",
    materials: ["brass"],
    prices: { brass: 260 },
    manufacturing_costs: { brass: 130 },
    creator_earnings: { brass: 130 },
    specs: "60mm x 45mm x 40mm",
    region: "europe",
    status: "published",
    made_to_order: true,
    _isDemo: true,
  },
  {
    id: "demo-5",
    name: "void_ring_11",
    description: "a minimal band with a precisely machined negative space running its full circumference. available in two profiles. the negative space catches light differently depending on the hour.",
    image_url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop&auto=format",
    creator_handle: "voidcraft",
    creator_name: "void craft",
    category: "jewelry",
    materials: ["silver", "gold"],
    prices: { silver: 160, gold: 420 },
    manufacturing_costs: { silver: 80, gold: 240 },
    creator_earnings: { silver: 80, gold: 180 },
    specs: "4mm or 6mm profile, sizes 4-14",
    region: "global",
    status: "published",
    made_to_order: true,
    _isDemo: true,
  },
  {
    id: "demo-6",
    name: "strata_earrings_04",
    description: "layered disc earrings referencing geological cross-sections. each pair is slightly unique due to the casting process. sold as a pair with sterling silver posts.",
    image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop&auto=format",
    creator_handle: "voidcraft",
    creator_name: "void craft",
    category: "jewelry",
    materials: ["silver", "gold"],
    prices: { silver: 195, gold: 510 },
    manufacturing_costs: { silver: 100, gold: 295 },
    creator_earnings: { silver: 95, gold: 215 },
    specs: "28mm diameter, sterling posts",
    region: "europe",
    status: "published",
    made_to_order: true,
    _isDemo: true,
  },
];