// Studio-side demo store fixtures used by CommissionPage
// Commerce demo artifacts (prices, orders) have been moved to platform.

export const DEMO_STORES = [
  {
    id: "demo-store-1",
    handle: "kaiform",
    display_name: "kai form",
    bio: "cad designer working at the intersection of jewelry and architecture. based in berlin.",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop&auto=format",
    banner_url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&h=300&fit=crop&auto=format",
    accent_color: "#84A48B",
    materials: ["silver", "brass", "gold"],
    tools: ["rhino", "grasshopper", "blender"],
    commission_open: true,
    hourly_rate: 80,
    turnaround_time: "2-3 weeks",
    store_heading: "objects at the edge of computation",
    social_instagram: "kaiform",
    _isDemo: true,
  },
  {
    id: "demo-store-2",
    handle: "orbitobjects",
    display_name: "orbit objects",
    bio: "sculptural wearables and functional objects. every piece is a conversation between material and form.",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&auto=format",
    banner_url: "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?w=800&h=300&fit=crop&auto=format",
    accent_color: "#558E9B",
    materials: ["silver", "brass"],
    tools: ["fusion 360", "keyshot"],
    commission_open: false,
    store_heading: "gravity-defying metal objects",
    social_instagram: "orbitobjects",
    _isDemo: true,
  },
  {
    id: "demo-store-3",
    handle: "voidcraft",
    display_name: "void craft",
    bio: "minimal, precise, considered. parametric jewelry from amsterdam.",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop&auto=format",
    banner_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=300&fit=crop&auto=format",
    accent_color: "#A386A9",
    materials: ["gold", "silver"],
    tools: ["rhino", "modo"],
    commission_open: true,
    hourly_rate: 120,
    turnaround_time: "3-4 weeks",
    store_heading: "precision in precious metals",
    _isDemo: true,
  },
];
